### ISSUE TITLE
V.1. Liste des commandes (3)

### ISSUE THREAD

**Issue by perezfelix** [TheStarrK/THP_Next_ECommerce#72]
1.  Créer une page d'index des Orders côté administrateur, attention, l'administrateur de doit pas voir les commandes non payées, uniquement celles qui ont le statut "Validée" ou "Traitée".
Deux choix : 
-Avoir deux colonnes "Commandes en attente" et "Commande traitée"
-Avoir deux onglets "Commandes en attente" et "Commande traitée"
Les commandes en attente doivent avoir un bouton pour changer leur statut de "en attente" à "traitée".

Information : Statut de la commande
0 : Non payée
1 : Payée
2 : Traitée

**Comment by TheStarrK** [comment]
Done
